CREATE TABLE [dbo].[Invitations]
(
	[Id] VARCHAR(40) NOT NULL, 
    [INVITATIONTYPE] VARCHAR NOT NULL, 
    [WORKGROUPCODE] VARCHAR(10) NULL, 
    [SYSTEMUSER] VARCHAR(53) NULL, 
    [NAME] VARCHAR(50) NOT NULL, 
    [CREATEUSER] VARCHAR(10) NOT NULL, 
    [CREATEDATE] INT NOT NULL, 
    [CREATETIME] VARCHAR(6) NOT NULL, 
    [INVITATIONNOTES] VARCHAR(250) NOT NULL, 
    [EXPIRYDATE] INT NOT NULL, 
    [INVITATIONSTATUS] VARCHAR(8) NOT NULL, 
    [REVOKEUSER] VARCHAR(10) NULL, 
    [REVOKEDATE] INT NULL, 
    [REVOKENOTES] VARCHAR(250) NULL
    CONSTRAINT [PK_INVITATIONS] PRIMARY KEY CLUSTERED ([Id] ASC)
)
