# Referenced by pipeline:
#   - https://dev.azure.com/amtsybex1/Mobile/_build?definitionId=683

trigger:
  branches:
    include:
      - develop
      - main

  paths:
    include:
      - 'Applications/Service Apps/Extract Adapter/'
      - 'Database/'
    exclude:
      - 'Applications/Service Apps/Extract Adapter/azure-*.yml'
      - 'Database/azure-*.yml'

pool: FieldSmart TFCloud (Build)

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - name: applicationBaseFolder
    value: 'Applications/Service Apps/Extract Adapter/'
  - name: artifactFolderName
    value: ExtractAdapter
  - name: artifactName
    value: extractadapter
  - group: 'Fusion_Common'


stages:
  # Build the FEA application using the templates.
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/buildUsingDocker.yml  # Template reference
    parameters:
      group_DOCKER_FBE: 'DOCKER_ACR_FUSIONBACKEND_TF'
      container_Path: '/app/extract-adapter.jar'
      artifact_Path: '/fea/extract-adapter.jar'
      application_Path: '/fea'

  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/dacpacBuild.yml  # Database CI template reference
 