
--Grant read only access to the Script Builder user on the following tables
GRANT SELECT ON AccessGroups TO SB_ADMIN
GO
GRANT SELECT ON DeclarationAudit TO SB_ADMIN
GO
GRANT SELECT ON FDMWGPAdmin TO SB_ADMIN
GO
GRANT DELETE, SELECT ON FDMScriptAccess TO SB_ADMIN
GO
GRANT SELECT ON HPCWorkGroups TO SB_ADMIN
GO
GRANT SELECT ON Labels TO SB_ADMIN
GO
GRANT SELECT ON ReturnedScripts TO SB_ADMIN
GO
GRANT SELECT ON ScriptItemTypes TO SB_ADMIN
GO
GRANT SELECT ON ScriptResults TO SB_ADMIN
GO
GRANT SELECT ON SoftVersions TO SB_ADMIN
GO
GRANT SELECT ON SystemFunctions TO SB_ADMIN
GO
GRANT SELECT ON ViewResultsDefn TO SB_ADMIN
GO
--Grant full access to the Script Builder user on the following tables
GRANT INSERT, SELECT , UPDATE, DELETE ON ActivityLog TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON AlertNomUser TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON Alerts TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON AutoDefect TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON AutoDisplay TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON CarryThrough TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON CSVFieldDefn TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON DeclarationMessage TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON DefectAlert TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON DefectNote TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON Defects TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON DefectSet TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON DefectSetDetail TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON DefUOMType TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON Devices TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON DisplayColour TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON EventTypeFieldRoles TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON EventTypes TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON FieldRoleTypes TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON FormatInputDef TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON FormatInputDefMe TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON GenCondAlert TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON GenDefAlert TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON GenNumValid TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON GroupFunctions TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON Help TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON HelpCategory TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON Item TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ItemCalculation TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ItemFileRef TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ItemRespRules TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ItemRespRulesRef TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON LicenseData TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON MeasureCategories TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON Media TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON NextStatusDef TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON OotAlert TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ProfileCategories TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ProfileScripts TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON PublishedScripts TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON RecordCardItem TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON RecordCardView TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON RefCat TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON RefItem TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON RefSubCat TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON RepeatGroups TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON RuntimeCalculations TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON RuntimeParameters TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScoreAlert TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON Script TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScriptCategory TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScriptItemRules TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScriptLinks TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScriptLock TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScriptPassword TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScriptProfiles TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScriptRefItem TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScriptStatusDef TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScriptStatusEventTypes TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ScriptVersions TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SpecialNote TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SPNoteCat TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SubDate TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SubDefaultMod TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SubLevel TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SubNumber TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SubScript TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SubScriptTrigger TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SubString TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SubUOMNumber TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SystemActivityLog TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SystemParams TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON SystemUsers TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON UnitOfMeasure TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON UOMNumValid TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ValFreeTextReq TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ValidationProperty TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ValidationType TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON ViewDefn TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON WorkflowRules TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON WorkflowRulesDef TO SB_ADMIN
GO
GRANT INSERT, SELECT , UPDATE, DELETE ON WorkOrderTypes TO SB_ADMIN
GO