# Referenced by pipeline:
#   - https://dev.azure.com/amtsybex1/Mobile/_build?definitionId=684

trigger:
  branches:
    include:
      - develop
      - main

  paths:
    include:
      - 'Applications/Web Apps/FDM Web Portal/'
    exclude:
      - 'Applications/Web Apps/FDM Web Portal/azure-*.yml'

pool: FieldSmart TFCloud (Build)

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - name: applicationBaseFolder
    value: 'Applications/Web Apps/FDM Web Portal/'
  - name: artifactFolderName
    value: FDMWebPortal
  - name: artifactName
    value: fdmwebportal
  - group: 'Fusion_Common'

stages:
  # Build the FDM application using the templates.
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/buildUsingDocker.yml  # Template reference
    parameters:
      group_DOCKER_FBE: 'DOCKER_ACR_FUSIONBACKEND_TF'
      container_Path: '/app/fdmwebportal.war'
      artifact_Path: '/fdm/fdmwebportal.war'
      application_Path: '/fdm'

  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/dacpacBuild.yml  # Database CI template reference

