# Default values for XML Loader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

configmap:
  configuration:
    # Database connection string
    DEFAULT_JDBC_URL: jdbc:sqlserver://sqlfg-web-uat-uksouth.database.windows.net:1433;databaseName=fieldsmart-uat;
    # Polling interval in milliseconds
    FXL_SCRIPTRESULT_PICKUP_POLLINGINTERVAL: '10000'  # Move to values-dev.yaml

labels:
  environment: uat
    
autoscaling:
  enabled: false
    