# Default values for mobile webservices.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configmap:
  configuration:
    # Database connection string
    DEFAULT_JDBC_URL: jdbc:sqlserver://sqlfg-web-aut-uksouth.database.windows.net:1433;databaseName=fieldsmart-aut;
    TENANT-URI_MWS: https://amt.v1.fieldsmarttest.com/aut/mobile
    TENANT-URI_PORTAL: https://amt.v1.fieldsmarttest.com/aut/fdm
    SERVER_SERVLET_CONTEXT_PATH: '/aut/'
    
labels:
  environment: aut
  
ingress:
  hosts:
    - host: amt.v1.fieldsmarttest.com
      paths:
        - path: /aut
          pathType: Prefix
  tls:
  - hosts:
    - amt.v1.fieldsmarttest.com
    secretName: aks-ingress-tls

probes:
  enabled: true
  livenessProbe:
    httpGet:
      path: /aut/actuator/health/liveness
      port: http
    initialDelaySeconds: 50
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /aut/actuator/health/readiness
      port: http
    initialDelaySeconds: 50
    periodSeconds: 20
    
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1