# Referenced by pipeline:
#   - https://dev.azure.com/amtsybex1/Mobile/_build?definitionId=687

# Explicitly set none for repository trigger
trigger:
  - none

#variables:
#  - name: applicationBaseFolder
#    value: 'Applications/Web Apps/FDM Web Portal/'
#  - name: automationTestRootFolder
#    value: 'Test Automation/'
#  - name: artifactFolderName
#    value: 'CI-pipeline/FDMWebPortal'
#  - name: artifactName
#    value: fdmportal
#  - group: 'Fusion_Common'

resources:
  # List each repository that we'll need
  #repositories:
  #- repository: FusionHelmTemplate
  #  type: git
  #  name: Mobile/fusion-helm-template
  #  ref: main
  #- repository: FusionDevOps
  #  type: git
  #  name: Mobile/fusion-devops
  #  ref: main

  pipelines:
    - pipeline: fusion-devops  # Name of the pipeline resource
      source: fusion-devops-ci # Name of the triggering pipeline
      #trigger:
      #  branches:
      #    include:
      #      - main
      #      - develop

stages:
  # Pull and run container on AUT
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploymentViaTerraform.yml  # Template reference
    parameters:
      envName: 'AUT'
      TenantClusterFoundation: 'Infra.Variables.Internal.Tenant-Cluster-Foundation.Aut'
      TenantHub: 'Infra.Variables.Internal.Tenant-Hub.Aut'
      TenantMain: 'Infra.Variables.Internal.Tenant-Main.Aut'
      TenantSQLDB: 'Infra.Variables.Internal.Tenant-Sqldb.Aut'
      TenantSharedLower: 'Infra.Variables.Internal.Tenant-Shared.Lower'
      HubNonProd: 'Infra.Variables.Internal.Hub.Nonprod'
      PlatformNonProd: 'Infra.Variables.Internal.Platform.Nonprod'
      TenantGatewayLower: 'Infra.Variables.Internal.Tenant-Gateway.PublicLower'

  # Pull and run container on Dev
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploymentViaTerraform.yml  # Template reference
    parameters:
      envName: 'DEV'
      TenantClusterFoundation: 'Infra.Variables.Internal.Tenant-Cluster-Foundation.Dev'
      TenantHub: 'Infra.Variables.Internal.Tenant-Hub.Dev'
      TenantMain: 'Infra.Variables.Internal.Tenant-Main.Dev'
      TenantSQLDB: 'Infra.Variables.Internal.Tenant-Sqldb.Dev'
      TenantSharedLower: 'Infra.Variables.Internal.Tenant-Shared.Lower'
      HubNonProd: 'Infra.Variables.Internal.Hub.Nonprod'
      PlatformNonProd: 'Infra.Variables.Internal.Platform.Nonprod'
      TenantGatewayLower: 'Infra.Variables.Internal.Tenant-Gateway.PublicLower'

  # Pull and run container on QA
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploymentViaTerraform.yml  # Template reference
    parameters:
      envName: 'QA'
      TenantClusterFoundation: 'Infra.Variables.Internal.Tenant-Cluster-Foundation.Qa'
      TenantHub: 'Infra.Variables.Internal.Tenant-Hub.Qa'
      TenantMain: 'Infra.Variables.Internal.Tenant-Main.Qa'
      TenantSQLDB: 'Infra.Variables.Internal.Tenant-Sqldb.Qa'
      TenantSharedLower: 'Infra.Variables.Internal.Tenant-Shared.Lower'
      HubNonProd: 'Infra.Variables.Internal.Hub.Nonprod'
      PlatformNonProd: 'Infra.Variables.Internal.Platform.Nonprod'
      TenantGatewayLower: 'Infra.Variables.Internal.Tenant-Gateway.PublicLower'

  ## Pull and run container on UAT
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploymentViaTerraform.yml  # Template reference
    parameters:
      envName: 'UAT'
      TenantClusterFoundation: 'Infra.Variables.Internal.Tenant-Cluster-Foundation.Uat'
      TenantHub: 'Infra.Variables.Internal.Tenant-Hub.Uat'
      TenantMain: 'Infra.Variables.Internal.Tenant-Main.Uat'
      TenantSQLDB: 'Infra.Variables.Internal.Tenant-Sqldb.Uat'
      TenantSharedLower: 'Infra.Variables.Internal.Tenant-Shared.Lower'
      HubNonProd: 'Infra.Variables.Internal.Hub.Nonprod'
      PlatformNonProd: 'Infra.Variables.Internal.Platform.Nonprod'
      TenantGatewayLower: 'Infra.Variables.Internal.Tenant-Gateway.PublicLower'

  #  # Pull and run container on Preprod UK South & UK West
  #- template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploymentViaTerraform.yml  # Template reference
  #  parameters:
  #    envname: 'PREPROD'
  #    envNameSouth: 'PREPROD_UKSOUTH'
  #    envNameWest: 'PREPROD_UKWEST'
  #    groupName: 'FusionCloudPenDeployment_MultiRegion_Preprod'
  #    appName: 'FDM'
  #    buildPoolName: 'FieldSmart PenTestCloud(Build)'
  #    deployPoolName: 'FieldSmart PenTestCloud(Deployment)'

  #  # Pull and run container on Prod UK South & UK West
  #- template: ${{variables['System.DefaultWorkingDirectory']}}/templates/deploymentViaHelmMultiRegion.yml  # Template reference
  #  parameters:
  #    envname: 'PROD'
  #    envNameSouth: 'PROD_UKSOUTH'
  #    envNameWest: 'PROD_UKWEST'
  #    groupName: 'FusionCloudPenDeployment_MultiRegion_Prod'
  #    appName: 'FDM'
  #    buildPoolName: 'FieldSmart PenTestCloud(Build)'
  #    deployPoolName: 'FieldSmart PenTestCloud(Deployment)'

