# Default values for Extract Adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

configmap:
  configuration:
    # Database connection string
    DEFAULT_JDBC_URL: jdbc:sqlserver://sqlfg-web-aut-uksouth.database.windows.net:1433;databaseName=fieldsmart-aut;

labels:
  environment: aut
    
autoscaling:
  enabled: false
    