# Referenced by pipeline:
#   - https://dev.azure.com/amtsybex1/Mobile/_build?definitionId=673

trigger:
  branches:
    include:
      - develop
      - main

  paths:
    include:
      - 'Applications/Service Apps/XML Loader/'
    exclude:
      - 'Applications/Service Apps/XML Loader/azure-*.yml'

pool: FieldSmart TFCloud (Build)

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
  - name: applicationBaseFolder
    value: 'Applications/Service Apps/XML Loader/'
  - name: artifactFolderName
    value: XmlLoader
  - name: artifactName
    value: xmlloader
  - group: 'Fusion_Common'


stages:
  # Build the XML Loader application using the templates.
  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/buildUsingDocker.yml  # Template reference
    parameters:
      group_DOCKER_FBE: 'DOCKER_ACR_FUSIONBACKEND_TF'
      container_Path: '/app/xml-loader.jar'
      artifact_Path: '/xml/xml-loader.jar'
      application_Path: '/xml'

  - template: ${{variables['System.DefaultWorkingDirectory']}}/templates/dacpacBuild.yml  # Database CI template reference
