server:
  port: 8071
  servlet:
    context-path: /integration/
  error:
    include-message: always

info:
  app:
    version: '@project.version@'
  
jdbc: 
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  connectionpool:
    max_size: 5
      
hibernate: 
  dialect: org.hibernate.dialect.SQLServerDialect
  show_sql: false
  format_sql: true 

default:
  jdbc:
    url: jdbc:sqlserver://myserver.ad.capita.co.uk:1433;databaseName=fieldsmart;
    username: 
    password: 
  instance:
    key: hiddensercretkey
     
folder:
  basePath: /home/fusion/fieldsmart
  
fileType:
  script: ${folder.basePath}/scripts/source
  config: ${folder.basePath}/configs
  script.reference: ${folder.basePath}/scripts/reference
  support.resource: ${folder.basePath}/scripts/support
  workorder: ${folder.basePath}/workorders

fileTransfer: 
  maxDaysActive: 2
     
fileDownload:
  maxDownloadSize: 30720000
  maxChunkSize: 1024000
  tempDir: ${folder.basePath}/temp/filedownloads
  
geofield:
  packages: ${folder.basePath}/packages
  
file: 
  upload:
    maxUploadSize:
    maxChunkSize: 1024000
    tempDir: ${folder.basePath}/temp/fileuploads
    dir:
      packages: ${folder.basePath}/packages
      other: ${folder.basePath}/upload/iws

assethistory:
  search:
    omit:
      scriptcodes: 

workorder:
  schema:
    filename: workorder.xsd
      
activity:
  logging:
    apps: 

auth0:
  audience: 

spring:
  jackson:
    default-property-inclusion: non-empty
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: 

accesstoken:
  key:
    private: /mnt/secrets-store/privatePKCS8

management:
  health:
    defaults:
      enabled: false


#Sample for okta
#auth0:
#  audience: ${AUTH0_AUDIENCE:0oarrap3epweLK7tI5d6}
#  
#spring:
#  jackson:
#    default-property-inclusion: non-empty
#  security:
#    oauth2:
#      resourceserver:
#        opaquetoken:
#          client-id: 0oarrap3epweLK7tI5d6
#          client-secret: Yi1IKmWTgNOGwa1PIWwonrYzxMUh0y824gDBo2Dg
#          introspection-uri: https://dev-55077234.okta.com/oauth2/v1/introspect
#        jwt:
#          issuer-uri: ${AUTH0_AUDIENCE:https://dev-55077234.okta.com}

#To externalize log4j properties link to an external configuration file
#logging:
#  config: "C:/Fieldreach/log4j2-spring.xml"