# Default Common values for mobile webservices across environments/tenants.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: acrplatdevshared.azurecr.io/fieldreachws
#  Override tag from command-line, example: --set image.tag=0.1.55-beta-develop.126
#  tag: "0.1.55-beta-develop.126"

deployment:
  containerPort: 8070
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: webservices-fieldsmart
    - name: fs-volume
      persistentVolumeClaim:
        claimName: azurefile
  volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
    - mountPath: "/home/fusion/fieldsmart"
      name: fs-volume


ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"

service:
  enabled: true
  port: 443
  env:
    - name: DEFAULT_JDBC_PASSWORD
      value: DbPassword
    - name: DEFAULT_JDBC_USERNAME
      value: DbUser
    - name: DEFAULT_INSTANCE_KEY
      value: InstanceKey
    - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
      value: JwtIssuerUri

configmap:
  enabled: true
  configuration:
    # Maximum number of days a file upload/download will remain active
    FILETRANSFER_MAXDAYSACTIVE: '2'
    # Maximum size of files that can be downloaded in bytes
    FILEDOWNLOAD_MAXDOWNLOADSIZE: '30720000'
    # Download chunk size in bytes
    FILEDOWNLOAD_MAXCHUNKSIZE: '1024000'
    # Maximum size of files that can be uploaded in bytes. 0 or blank for unlimited
    FILE_UPLOAD_MAXUPLOADSIZE: ''
    # Upload chunk size in bytes
    FILE_UPLOAD_MAXCHUNKSIZE: '1024000'
    # Comma delimited list of script codes to omit from asset history result search
    ASSETHISTORY_SEARCH_OMIT_SCRIPTCODES: ''
    # Location to retain WORKSTATUS transactions. Must blank, DIR or JMS
    FRTRANSACTION_WORKSTATUS_DESTINATIONTYPE: 'DIR'
    # Folder/Queue name to retain WORKSTATUS transactions
    FRTRANSACTION_WORKSTATUS_DESTINATION: ${folder.basePath}/transactions
    # Comma delimited list of statuses that transactions should be retained for.
    FRTRANSACTION_WORKSTATUS_RETAINSTATUSLIST: ''
    # Auth Audience
    AUTH_AUDIENCE: tn47mNO4J4gySXDG3bhuc11miYI5Jgnh

    # Auth Username
    AUTH_USERNAME: name
    # Auth Usercode  
    AUTH_USERCODE: nickname
    # Issuer URI - N.B. The trailing slash is important.
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://mcamt.eu.auth0.com/
    # LOG level.
    LOGGING_LEVEL_ROOT: #{LOGGINGLEVEL}#
    # Log Level  for HIKARI
    LOGGING_LEVEL_COM_ZAXXER_HIKARI: #{LOGHIKARI}#
    # Log level for SPRINGFRAMEWORK
    LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: #{LOGSPRINGFRAMEWORK}#
    # Logging level for Hibernate
    LOGGING_LEVEL_ORG_HIBERNATE: #{LOGHIBERNATE}#
    # Logging Level for AMTSYBEX 
    LOGGING_LEVEL_COM_AMTSYBEX: #{LOGAMTSYBEX}#
    # Logging Level for APACHE 
    LOGGING_LEVEL_ORG_APACHE: #{LOGAPACHE}#
    ACTIVITY_LOGGING_APPS: WM


# resources:
  # requests:
    # memory: "500Mi"
    # cpu: "50m"
  # limits:
    # memory: "700Mi"
    # cpu: "100m"
    
secretProviderClass:
  enabled: true
  name: webservices-fieldsmart
  secretObjects:
    type: Opaque
    data:
      - key: DbPassword
        objectName: DbPassword
      - key: DbUser
        objectName: DbUser
      - key: InstanceKey
        objectName: InstanceKey
      - key: JwtIssuerUri
        objectName: JwtIssuerUri
  keyVaultSecrets:
    - objectName: DbPassword
      objectType: secret
      objectVersion: ''
    - objectName: DbUser
      objectType: secret
      objectVersion: ''
    - objectName: InstanceKey
      objectType: secret
      objectVersion: ''
    - objectName: JwtIssuerUri
      objectType: secret
      objectVersion: ''
    - objectName: public
      objectType: secret
      objectVersion: ''
