CREATE TABLE [dbo].[ConfigurationFiles]
(
	[CONFIGFILENAME] VARCHAR(25) NOT NULL PRIMARY KEY,
	[PUBLISHEDDATE] INT NOT NULL,
    [PUBLISHEDTIME] VARCHAR(6) NOT NULL,
    [SYSTEMUSER] VARCHAR(53) NOT NULL,
    [CONFIGFILETYPE] VARCHAR(12) NOT NULL,
	[WORKGROUPCODE] VARCHAR(10),
	[CONFIGFILE] IMAGE NOT NULL,
	[CHECKSUM] VARCHAR(128) NOT NULL
)
