CREATE TABLE [dbo].[LWSessionHistory] (
    [LWSESSIONID]      VARCHAR (24)  NOT NULL,
    [TRANSTYPE]        VARCHAR (10)  NOT NULL,
    [LOGDATE]          INT           NOT NULL,
    [LOGTIME]          INT           NOT NULL,
    [SESSIONSTARTDATE] INT           NULL,
    [SESSIONSTARTTIME] INT           NULL,
    [DURATION]         INT           NULL,
    [DEVICEID]         VARCHAR (255) NULL,
    [ADDITIONALTEXT]   VARCHAR (120) NULL,
    [USERTYPE]         VARCHAR (1)   NOT NULL,
    [USERCODE]         VARCHAR (32)  NOT NULL,
    [TRANSFILENAME]    VARCHAR (255) NULL,
    [MESSAGE]          VARCHAR (200) NULL,
    CONSTRAINT [PK_LWSESSIONHISTORY] PRIMARY KEY CLUSTERED ([LWSESSIONID] ASC, [TRANSTYPE] ASC, [LOGDATE] ASC, [LOGTIME] ASC)
);

