CREATE TABLE [dbo].[LWSession] (
    [LWSESSIONID]       VARCHAR (24) NOT NULL,
    [USERCODE]          VARCHAR (32) NOT NULL,
    [WORKORDERNO]       VARCHAR (20) NOT NULL,
    [DISTRICTCODE]      VARCHAR (4)  NULL,
    [LOCATION]          VARCHAR (80) NOT NULL,
    [PHONENO]           VARCHAR (20) NULL,
    [SESSIONSTATUS]     VARCHAR (1)  NOT NULL,
    [SESSIONSTARTDATE]  INT          NOT NULL,
    [SESSIONSTARTTIME]  INT          NOT NULL,
    [SESSIONEXPIREDATE] INT          NOT NULL,
    [SESSIONEXPIRETIME] INT          NOT NULL,
    CONSTRAINT [PK_LWSESSION] PRIMARY KEY CLUSTERED ([LWSESSIONID] ASC)
);

