CREATE TABLE [dbo].[SystemParams] (
    [FDCSSetup]          VARCHAR (1)   NULL,
    [SysAlertUser]       VARCHAR (10)  NULL,
    [MaxPasswordDays]    INT           NULL,
    [Logging]            INT           NULL,
    [PrevCol]            VARCHAR (12)  NULL,
    [OtCol]              VARCHAR (12)  NULL,
    [HPCMailBox]         VARCHAR (50)  NULL,
    [EditResults]        INT           NULL,
    [CompanyName]        VARCHAR (40)  NOT NULL,
    [CompanyLogo]        VARCHAR (40)  NULL,
    [MaxDefects]         INT           NULL,
    [HPCPhotoDir]        VARCHAR (80)  NULL,
    [PCPhotoDir]         VARCHAR (120) NULL,
    [HPCVoiceDir]        VARCHAR (80)  NULL,
    [PCVoiceDir]         VARCHAR (120) NULL,
    [MaxResultSets]      INT           NULL,
    [HPCLoginScope]      VARCHAR (1)   NULL,
    [HPCPin]             INT           NULL,
    [WOExtractDir]       VARCHAR (80)  NULL,
    [SyncType]           VARCHAR (3)   NULL,
    [SyncServerIp]       VARCHAR (20)  NULL,
    [SyncServerLogin]    VARCHAR (15)  NULL,
    [SyncServerPass]     VARCHAR (10)  NULL,
    [SyncDirOut]         VARCHAR (80)  NULL,
    [SyncDirIn]          VARCHAR (80)  NULL,
    [SyncDirectImport]   INT           NULL,
    [ScriptLoadPBar]     INT           NULL,
    [SysUserClass]       VARCHAR (20)  NULL,
    [HPCUserClass]       VARCHAR (20)  NULL,
    [WGLookUpClassA]     VARCHAR (20)  NULL,
    [WGLookUpClassB]     VARCHAR (20)  NULL,
    [DeviceClass]        VARCHAR (20)  NULL,
    [ProjectName]        VARCHAR (30)  NULL,
    [LWRefresh]          INT           NULL,
    [MinPasswdLen]       INT           NULL,
    [MinPasswdDigits]    INT           NULL,
    [CHRL]               VARCHAR (202) NULL,
    [InstanceName]       VARCHAR (30)  NULL,
    [SchemaName]         VARCHAR (30)  NULL,
    [ReportTableSpace]   VARCHAR (30)  NULL,
    [MaxLoginRetries]    INT           NULL,
    [HPCPasswordExpire]  INT           NULL,
    [BaseURL]            VARCHAR (200) NULL,
    [Timeout]            INT           NULL,
    [DataSec]            VARCHAR (10)  NULL,
    [MapKey]             VARCHAR (100) NULL,
    [AutoDispatch]       INT           NULL,
    [AutoDispatchWindow] INT           NULL,
    [AutoDispatchType]   VARCHAR (1)   NULL, 
    [MapKeyBing] VARCHAR(150) NULL
);

