CREATE TABLE [dbo].[Media] (
    [MEDIAID]   INT           NOT NULL,
    [DATEADDED] INT           NULL,
    [USERADDED] VARCHAR (10)  NULL,
    [FILENAME]  VARCHAR (200) NULL,
    [FILEDESC]  VARCHAR (50)  NULL,
    [FILETYPE]  VARCHAR (20)  NULL,
    [CONTENT]   IMAGE         NULL,
    [REFONLY]   INT           NULL,
    CONSTRAINT [PK_MEDIA] PRIMARY KEY CLUSTERED ([MEDIAID] ASC)
);

