CREATE TABLE [dbo].[Retscript_Edit_Archive] (
    [ReturnID]         INT           NOT NULL,
    [ScriptID]         INT           NOT NULL,
    [ScriptCode]       VARCHAR (15)  NOT NULL,
    [ScriptStatus]     VARCHAR (5)   NOT NULL,
    [Project]          VARCHAR (30)  NULL,
    [DeviceID]         VARCHAR (255) NULL,
    [WorkOrderNo]      VARCHAR (20)  NULL,
    [WorkOrderDesc]    VARCHAR (80)  NULL,
    [EquipNo]          VARCHAR (30)  NULL,
    [EquipDesc]        VARCHAR (80)  NULL,
    [AltEquipRef]      VARCHAR (30)  NULL,
    [SummaryDesc]      VARCHAR (80)  NULL,
    [RunType]          VARCHAR (2)   NULL,
    [StartDate]        INT           NULL,
    [StartTime]        INT           NULL,
    [CompleteDate]     INT           NULL,
    [CompleteTime]     INT           NULL,
    [Duration]         INT           NULL,
    [CompleteUser]     VARCHAR (20)  NULL,
    [CompleteCode]     VARCHAR (5)   NULL,
    [WorkGroup]        VARCHAR (30)  NULL,
    [ReturnDate]       INT           NULL,
    [ResultStatus]     VARCHAR (15)  NULL,
    [ReturnFile]       VARCHAR (255) NULL,
    [UploadStatus]     VARCHAR (15)  NULL,
    [UploadDate]       INT           NULL,
    [ResAssocCode]     VARCHAR (70)  NULL,
    [TotalWeightScore] INT           NULL,
    CONSTRAINT [PK_RETSCRIPT_EDIT_ARCHIVE] PRIMARY KEY CLUSTERED ([ReturnID] ASC)
);

